/**
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, 
 * the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values 
    do not exceed four million, find the sum of the even-valued terms.
    Jun 26th 2022 - 9:45 PM
 */

console.log(((max) => {
    const fibo = [1,2];
    for(let i = 2; i < max; i++) {
        if(fibo[i-2] + fibo[i-1] < max) {
            fibo.push(fibo[i-2] + fibo[i-1]);
        } else {
            break;
        }
    };
    return fibo.filter((v) => v % 2 === 0).reduce((acc, n) => acc + n, 0);
})(4000000));